apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: req-counter-ingress
  labels:
    name: req-counter-ingress
spec:
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: req-counter-service
              port:
                number: 80